# Generated by Django 3.1.7 on 2021-03-22 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('appointment_schedules', models.IntegerField(default=0)),
                ('doctor_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('staff_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('year_of_employment', models.DateField()),
                ('level', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('patient_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('genotype', models.CharField(max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('med_number', models.CharField(max_length=10)),
                ('diagnosis', models.CharField(max_length=500)),
                ('treatments', models.CharField(max_length=500)),
                ('medications', models.CharField(max_length=500)),
                ('test_required', models.CharField(max_length=150, null=True)),
                ('appointment_history', models.CharField(max_length=50)),
                ('updated_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateField()),
                ('appointment_reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('appointment_number', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.patient')),
            ],
        ),
    ]
