# Generated by Django 3.1.7 on 2021-03-23 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyHospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=500)),
                ('no_of_doctors', models.FloatField(max_length=500)),
                ('name_of_doctors', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(default='active', max_length=15)),
                ('date_created', models.DateField(default=datetime.date(2021, 3, 23))),
                ('date_updated', models.DateField(null=True)),
                ('payment_account_number', models.CharField(max_length=20)),
                ('payment_pin', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.doctor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='payment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.patient'),
        ),
        migrations.AddField(
            model_name='departments',
            name='department_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.doctor'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.payment'),
            preserve_default=False,
        ),
    ]
