# Generated by Django 3.1.7 on 2021-03-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyHospitalApp', '0003_departmenthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MyHospitalApp.departmenthead'),
        ),
    ]
