# Generated by Django 3.1.7 on 2021-03-24 12:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyHospitalApp', '0005_remove_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_number',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 24)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 3, 24)),
        ),
    ]
